name: Actions Workflow

on:
  push:
    branches:
      - master
      - 'feature/*' # matches feature/*
      - 'feature/**' #master feature/feat/a
    # branches-ignore: 
    #   - dev/*
    tags: 
      - v1
    # paths:
    #   - '**.js'
    #   - '!test.js'   # can run for all JS files except test.js file
  repository_dispatch:
    types: [build]
#   push: 
#   schedule:
#     - cron: "0/5 * * * *"
#     - cron: "0/6 * * * *"
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pws
          ls
    